services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
